### ISSUE TITLE
[Bug] zdict interactive mode failed with python3.6 on OSX

### ISSUE THREAD

**Issue by chengchingwen** [zdict/zdict#121] opened 2017-04-03 19:49 UTC
OS version: macOS Sierra 10.12.3
python: python3.6
zdict: 0.9.6

I try to open zdict in the command line and get the following error message 

```
Traceback (most recent call last):
  File "/Users/chengchingwen/pypyenv/bin/zdict", line 4, in <module>
    zdict.main()
  File "/Users/chengchingwen/pypyenv/lib/python3.6/site-packages/zdict/zdict.py", line 310, in main
    execute_zdict(args)
  File "/Users/chengchingwen/pypyenv/lib/python3.6/site-packages/zdict/zdict.py", line 294, in execute_zdict
    interactive_mode(args)
  File "/Users/chengchingwen/pypyenv/lib/python3.6/site-packages/zdict/zdict.py", line 267, in interactive_mode
    zdict = MetaInteractivePrompt(args)
  File "/Users/chengchingwen/pypyenv/lib/python3.6/site-packages/zdict/zdict.py", line 224, in __init__
    dictionary_map[d](self.args) for d in self.args.dict
  File "/Users/chengchingwen/pypyenv/lib/python3.6/site-packages/zdict/zdict.py", line 224, in <genexpr>
    dictionary_map[d](self.args) for d in self.args.dict
  File "/Users/chengchingwen/pypyenv/lib/python3.6/site-packages/zdict/dictionary.py", line 23, in __init__
    self.db.connect()
  File "/Users/chengchingwen/pypyenv/lib/python3.6/site-packages/peewee.py", line 3659, in connect
    raise OperationalError('Connection already open')
peewee.OperationalError: Connection already open
Exception ignored in: <bound method MetaInteractivePrompt.__del__ of <zdict.zdict.MetaInteractivePrompt object at 0x11000ce80>>
Traceback (most recent call last):
  File "/Users/chengchingwen/pypyenv/lib/python3.6/site-packages/zdict/zdict.py", line 237, in __del__
    del self.dicts
AttributeError: dicts
```

**Comment by wdv4758h** [comment] 2017-04-04 03:02
it looks like duplicate with https://github.com/zdict/zdict/issues/119
@chengchingwen can you try the master branch ? I think this issue is already fixed at master branch.

**Comment by M157q** [comment] 2017-04-04 03:18
I think the problem is that we haven't bump into a new version for the patch in #119.
So, the newest version on pypi is 0.9.6 which is without the patch.
Let me bump into a new version quickly, then this issue can be closed.

**Comment by wdv4758h** [comment] 2017-04-04 03:20
Yes, we should bump the version.

**Comment by chengchingwen** [comment] 2017-04-04 03:23
I tried the master branch and it worked fine.

**Comment by wdv4758h** [comment] 2017-04-04 04:14
the new version is released, so close this issue

**Closed by wdv4758h** 2017-04-04 04:14 UTC

**Comment by M157q** [comment] 2017-04-04 04:20
@chengchingwen [v0.9.7 has released on pypi](https://pypi.python.org/pypi/zdict/0.9.7).
Could you try again and see if it works?

**Comment by chengchingwen** [comment] 2017-04-04 05:25
@M157q v0.97 works well
